### ISSUE TITLE
js-ipfs tests are failing

### ISSUE THREAD

**Issue by richardschneider** [ipfs/interface-ipfs-core#165]
```
module.js:515
    throw err;
    ^

Error: Cannot find module 'aegir/fixtures'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\interface-ipfs-core\src\files.js:12:21)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\interface-ipfs-core\src\index.js:4:17)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\Owner\Documents\GitHub\js-ipfs\test\core\interface\block.js:4:14)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Suite.describe (c:\Users\Owner\Documents\GitHub\js-ipfs\test\core\interface\interface.spec.js:8:3)
    at Object.create (C:\Users\Owner\AppData\Roaming\npm\node_modules\aegir\node_modules\mocha\lib\interfaces\common.js:112:19)
    at context.describe.context.context (C:\Users\Owner\AppData\Roaming\npm\node_modules\aegir\node_modules\mocha\lib\interfaces\bdd.js:44:27)
    at Object.<anonymous> (c:\Users\Owner\Documents\GitHub\js-ipfs\test\core\interface\interface.spec.js:7:1)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\aegir\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\Owner\AppData\Roaming\npm\node_modules\aegir\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\Users\Owner\AppData\Roaming\npm\node_modules\aegir\node_modules\mocha\lib\mocha.js:514:10)
    at Object.<anonymous> (C:\Users\Owner\AppData\Roaming\npm\node_modules\aegir\node_modules\mocha\bin\_mocha:484:18)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by richardschneider** [comment]
It looks like `aegir` should be a dependency and **NOT** a dev dependency .

@diasdavid do we really want this!

**Comment by diasdavid** [comment]
@richardschneider looks like you had some issue with your npm install, which npm and node version are you using?

**Comment by richardschneider** [comment]
@diasdavid fairly recent versions

> npm -v
> 5.4.2
> node -v
>v8.8.1

Read the code, it does `require ('aegit/fixtures')`

**Comment by diasdavid** [comment]
This is a different behavior in Windows then. I'll take the PR
