### ISSUE TITLE
Error: Invalid version, must be a number equal to 1 or 0

### ISSUE THREAD

**Issue by tyvdh** [ipfs/interface-ipfs-core#358]
Running a number of `ipfs.dag.put` requests flawlessly and then running `ipfs.pin.add` on each of their cids. However when I go to `ipfs.pin.ls` I get a long list of these errors.

```
Error: Invalid version, must be a number equal to 1 or 0
    at Function.validateCID (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/cids/src/index.js:235:13)
    at new CID (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/cids/src/index.js:105:9)
    at toB58String (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipfs/src/core/components/pin.js:26:10)
    at nodes.map (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipfs/src/core/components/pin.js:60:35)
    at Array.map (<anonymous>)
    at dag._getRecursive (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipfs/src/core/components/pin.js:60:12)
    at mapAsync (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipfs/src/core/components/dag.js:160:11)
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/map.js:32:9
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/once.js:12:16
    at eachOfArrayLike (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/eachOf.js:53:9)
    at exports.default (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/eachOf.js:9:5)
    at _asyncMap (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/map.js:25:5)
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/doParallel.js:20:16
    at self.dag.get (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipfs/src/core/components/dag.js:155:9)
    at _get (/Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/ipld/src/index.js:143:9)
    at /Users/tyler/Desktop/Web/Colorglyph-2.0/colorglyph-express/node_modules/async/internal/once.js:12:16
```

Any ideas?

**Comment by tyvdh** [comment]
Looks like if I set the `options` to `{recursive: false}` it works as expected. Huh. /shrug

**Comment by tyvdh** [comment]
Seems odd to me that you can pin it successfully but cannot list it

**Comment by diasdavid** [comment]
@tyvdh I believe that is because the Pinning Service is not yet CIDv1 friendly

**Comment by lidel** [comment]
@tyvdh  Another thing to check is the version of [cids](https://www.npmjs.com/package/cids) library, make sure you use >= v0.5.5.

**Comment by alanshaw** [comment]
> @tyvdh I believe that is because the Pinning Service is not yet CIDv1 friendly

Yes, this is my understanding too. Needs a fix!
