### ISSUE TITLE
Create a working example

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/interface-ipfs-core#43]
I want to be able to use this. I made a repository following the instructions in this Reamde, I think, and I got nowhere. Can someone help me through this? 

[interface-ipfs-core-example](https://github.com/RichardLitt/interface-ipfs-core-example)

To run:

```
$ mocha test.js
/Users/richard/src/interface-ipfs-core-example/test.js:13
test.all(common)
     ^

TypeError: test.all is not a function
    at Object.<anonymous> (/Users/richard/src/interface-ipfs-core-example/test.js:13:6)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/richard/.nvm/versions/node/v5.0.0/lib/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/richard/.nvm/versions/node/v5.0.0/lib/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/richard/.nvm/versions/node/v5.0.0/lib/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/richard/.nvm/versions/node/v5.0.0/lib/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by dignifiedquire** [comment]
Take a look at https://github.com/ipfs/js-ipfs/blob/master/test/core/both/test-files.js

**Comment by RichardLitt** [comment]
Thanks. See #44.

**Comment by diasdavid** [comment]
@RichardLitt hope that @dignifiedquire pointer helped you. This repo are a set of tests that can be used against a working implementation of the ipfs-core api, that's all :)
